In [2]:
import pandas as pd
import geopandas as gpd

In [8]:
data = gpd.read_file("assets/celltowers.geojson")
data.head(5)

,FID,LICENSEE,CALLSIGN,LOCADD,LOCCITY,LOCCOUNTY,LOCSTATE,NEPA,LIC_ID,geometry
0,25,"NEW CINGULAR WIRELESS PCS, LLC",KNKA679,16400 CLEAR CREEK ROAD NORTHWEST,POULSBO,KITSAP,WA,N,11510,POINT (-122.68891 47.71111)
1,26,"NEW CINGULAR WIRELESS PCS, LLC",KNKA679,8971 SE VIEW PARK ROAD,PORT ORCHARD,KITSAP,WA,N,11510,POINT (-122.53391 47.48031)
2,27,"NEW CINGULAR WIRELESS PCS, LLC",KNKA679,63 MARITIME ROAD,QUILCENE,JEFFERSON,WA,N,11510,POINT (-122.82171 47.69191)
3,28,"NEW CINGULAR WIRELESS PCS, LLC",KNKA700,0.5 MILES EAST OF ROUTE 12,UNION GAP,YAKIMA,WA,N,11511,POINT (-120.45781 46.53061)
4,29,"NEW CINGULAR WIRELESS PCS, LLC",KNKA700,EAST END OF SNIPES MOUNTAIN/NO ADDRESS,SUNNYSIDE,YAKIMA,WA,N,11511,POINT (-120.06331 46.30781)

In [47]:
wa_data = gpd.read_file("assets/wacounties.json")
wa_df_data = pd.DataFrame(wa_data);
wa_df_data

,GEOID,NAME,POP,AREA,geometry
0,53001,Adams,18728,1929,"POLYGON ((-118.97952 47.26171, -118.98053 47.1..."
1,53003,Asotin,21623,640,"POLYGON ((-117.22890 46.46231, -117.22876 46.4..."
2,53005,Benton,175177,1760,"POLYGON ((-119.87406 46.62858, -119.87509 46.5..."
3,53007,Chelan,72453,2993,"POLYGON ((-121.11361 47.59714, -121.11081 47.5..."
4,53009,Clallam,71404,2670,"POLYGON ((-123.24903 48.28431, -123.25129 48.2..."
5,53011,Clark,425363,656,"POLYGON ((-122.78552 45.85053, -122.78570 45.8..."
6,53013,Columbia,4078,873,"POLYGON ((-118.22893 46.59360, -118.22841 46.5..."
7,53015,Cowlitz,102410,1166,"POLYGON ((-123.21306 46.17254, -123.16642 46.1..."
8,53017,Douglas,38431,1849,"POLYGON ((-120.00707 47.22005, -120.00485 47.2..."
9,53019,Ferry,7551,2258,"POLYGON ((-118.83691 49.00031, -118.83647 48.9..."
10,53021,Franklin,78163,1265,"POLYGON ((-119.45322 46.67924, -119.45724 46.6..."
11,53023,Garfield,2266,718,"POLYGON ((-117.85185 46.62477, -117.85284 46.5..."
12,53025,Grant,89120,2791,"POLYGON ((-118.98239 47.96202, -119.10404 47.9..."
13,53027,Grays Harbor,72797,2224,"POLYGON ((-123.20206 47.08490, -123.26617 47.0..."
14,53029,Island,78506,517,"POLYGON ((-122.42952 47.82761, -122.42295 47.8..."
15,53031,Jefferson,29872,2183,"POLYGON ((-122.95239 48.34971, -122.95310 48.2..."
16,53033,King,1931249,2307,"POLYGON ((-122.53672 47.40299, -122.53843 47.3..."
17,53035,Kitsap,251133,566,"POLYGON ((-122.95047 47.60627, -122.96947 47.5..."
18,53037,Kittitas,40915,2334,"POLYGON ((-121.37967 47.08676, -121.37746 47.0..."
19,53039,Klickitat,20318,1904,"POLYGON ((-119.86627 46.04066, -119.92917 46.0..."
20,53041,Lewis,75455,2436,"POLYGON ((-122.20272 46.76263, -122.28240 46.7..."
21,53043,Lincoln,10570,2340,"POLYGON ((-118.97350 47.94357, -118.97532 47.8..."
22,53045,Mason,60699,1051,"POLYGON ((-123.20206 47.08490, -123.12626 47.0..."
23,53047,Okanogan,41120,5315,"POLYGON ((-118.83691 49.00031, -118.87616 49.0..."
24,53049,Pacific,20920,1224,"POLYGON ((-124.18121 46.79374, -124.17322 46.7..."
25,53051,Pend Oreille,13001,1425,"POLYGON ((-117.42950 49.00048, -117.43015 48.9..."
26,53053,Pierce,795225,1806,"POLYGON ((-121.37967 47.08676, -121.39306 47.0..."
27,53055,San Juan,15769,621,"POLYGON ((-123.00847 48.83134, -123.00886 48.7..."
28,53057,Skagit,116901,1920,"POLYGON ((-122.73974 48.40551, -122.69165 48.4..."
29,53059,Skamania,11066,1684,"POLYGON ((-122.24563 46.05393, -122.24588 45.9..."
30,53061,Snohomish,713335,2197,"POLYGON ((-122.43804 47.77812, -122.33532 47.7..."
31,53063,Spokane,471221,1781,"POLYGON ((-117.04002 47.25927, -117.03979 47.3..."
32,53065,Stevens,43531,2540,"POLYGON ((-118.19684 49.00029, -118.19747 48.9..."
33,53067,Thurston,252264,773,"POLYGON ((-123.20206 47.08490, -123.20085 47.0..."
34,53069,Wahkiakum,3978,287,"POLYGON ((-123.72832 46.26454, -123.68761 46.2..."
35,53071,Walla Walla,58781,1299,"POLYGON ((-118.22893 46.59360, -118.24426 46.6..."
36,53073,Whatcom,201140,2503,"POLYGON ((-123.00847 48.83134, -122.79187 48.7..."
37,53075,Whitman,44776,2178,"POLYGON ((-117.85185 46.62477, -117.82314 46.6..."
38,53077,Yakima,243231,4311,"POLYGON ((-121.45635 46.78374, -121.45251 46.7..."

In [21]:
# use filtered dataframe to find unique values
print(sorted(wa_data.LICENSEE.unique()))

['AT&T MOBILITY WIRELESS OPERATIONS HOLDINGS, INC.', 'EASTERN SUB-RSA LIMITED PARTNERSHIP', 'MCDANIEL CELLULAR TELEPHONE COMPANY', 'NEW CINGULAR WIRELESS PCS, LLC', 'OREGON RSA #2, INC.', 'RCC MINNESOTA, INC.', 'SEATTLE SMSA LIMITED PARTNERSHIP', 'USCOC OF RICHLAND, INC.', 'USCOC OF WASHINGTON-4, INC.', 'VERIZON WIRELESS (VAW), LLC', 'WASHINGTON RSA #8 LIMITED PARTNERSHIP', 'WESTERN SUB-RSA LIMITED PARTNERSHIP', 'YAKIMA MSA LIMITED PARTNERSHIP']

In [39]:
# wa_data needs to contain all the count of cell towers in each individual county
county_group = data.groupby("LOCCOUNTY", as_index=False).count()
county_group['count'] = county_group.FID
result = county_group[['LOCCOUNTY', 'count']]
result['LOCCOUNTY'] = result['LOCCOUNTY'].str.lower().str.capitalize()
result.head(3)

# rename columns for merge
result.columns =['NAME', 'count']
result.head(3)

C:\Users\kevin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     NAME  count
0   Adams     15
1  Asotin      5
2  Benton     21

In [61]:
# merge two dataframes for export json file
final = wa_data.merge(result, on = "NAME")

In [64]:
# convert back to json
with open('wacountydata.json', 'w') as f:
        f.write(final.to_json())